### ISSUE TITLE
Add Media Information

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Resource-Container#52]
We need a way to encode audio/video information into an RC.

**Comment by neutrinog** [comment]
@jag3773 what's the purpose of including the length of the audio file?
If they download the file they can easily determine how long it is.

Also, for the size of the file they can easily retrieve that information from the server before download by first requesting the head and retrieving 'content-length'.

If we are going to condense the media definitions into single links with wildcards we won't be able to keep the above information in the yaml.

This is what I have so far:

```yaml
  ---
  projects:
    -
      identifier: 'obs'
      version: '4'
      media:
        -
          identifier: 'mp3'
          version: '1'
          quality:
            - '64kbps'
            - '32kbps'
          location: 'https://cdn.door43.org/en/obs/v4/media/mp3/v1/en_obs_{chapter}_{quality}.mp3'
        -
          identifier: 'mp4'
          version: '1'
          quality:
            - '360p'
            - '720p'
          location: 'https://cdn.door43.org/en/obs/v4/media/mp4/v1/en_obs_{chapter}_{quality}.mp4'
        -
          identifier: 'pdf'
          version: '1'
          location: 'https://cdn.door43.org/en/obs/v4/media/pdf/v1/en_obs.pdf'
```
